# Travis CI configuration for GenSVM

matrix:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
        - docker
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y libatlas-base-dev liblapack-dev liblapacke-dev;
      env:
        - CC="gcc"
        - PYTHON="python3"
        - PIP="pip3"
        - CIBW_BEFORE_BUILD="yum install -y atlas-devel lapack-devel && pip install numpy Cython"

    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install openblas
        - brew install lapack
      env:
        - CC="gcc"
          # avoids build errors on OSx
        - CFLAGS="-fcommon"
        - PYTHON="python3"
        - PIP="pip3"
        - CIBW_BEFORE_BUILD="pip install numpy Cython"
    - os: windows
      language: shell
      before_install:
        - choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:/c/ProgramData/chocolatey/bin:$PATH
        - PYTHON="python"
        - PIP="pip"
        - CIBW_BEFORE_BUILD="/c/cibw/nuget.exe install lapacke -OutputDirectory /cibw/lapacke -Verbosity detailed && dir C:\cibw\lapacke && pip install numpy Cython"

env:
  global:
    # No longer actively maintaining gensvm for Python 2.7
    - CIBW_SKIP="cp27-*"
    # Run the unit tests on the wheels that are created
    - CIBW_TEST_COMMAND="python -VV && python -m unittest discover -f -s {project}/test"

      #install:
      #  - $PIP install numpy
      #  - $PIP install -e .[dev]
      #  - $PYTHON -m unittest discover -v -f -s ./test

script:
  - $PIP install cibuildwheel==1.0.0
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
