language: python
python:
  - "3.6"

env:
  - CC="gcc"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y blas

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install nose Cython
  - python setup.py build_ext --inplace

script:
  - nosetests -v
