# Travis CI configuration for GenSVM

matrix:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
        - docker
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y libatlas-base-dev liblapack-dev liblapacke-dev;
      env:
        - CC="gcc"
        - PYTHON="python3"
        - PIP="pip3"
        - CIBW_BEFORE_BUILD="yum install -y atlas-devel lapack-devel && pip install numpy"

    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install openblas
        - brew install lapack
      env:
        - CC="gcc"
        - PYTHON="python3"
        - PIP="pip3"
        - CIBW_BEFORE_BUILD="pip install numpy"

    - os: windows
      language: shell
      before_install:
        - choco install python3 --version 3.6.8 --no-progress -y
        - choco install git
        - /c/tools/cygwin/setup-x86.exe -q -P lapack-3.8.0-1,openblas-0.3.7-1
          #- /c/ProgramData/chocolatey/bin/cyg-get.bat lapack-3.8.0-1 
          #openblas-0.3.7-1
          #- choco install cyg-get --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:/c/ProgramData/chocolatey/bin:$PATH
        - PYTHON="python"
        - PIP="pip"
        - CIBW_BEFORE_BUILD="pip install numpy"

env:
  - CIBW_TEST_COMMAND="python -VV && python -m unittest discover -f -s {project}/test

env:
  - CC="gcc"

install:
  - $PIP install numpy
  - $PIP install -e .[dev]
  - $PYTHON -m unittest discover -v -f -s ./test

script:
  - $PIP install cibuildwheel==1.0.0
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
