language: python
python:
  - "3.6"

env:
  - CC="gcc"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install nose
  - python setup.py build_ext --inplace

script:
  - nosetests -v
