name: build

on:
  push:
  pull_request:
  schedule:
    - cron: 42 5 * * */14

jobs:
  test:
    name: Unit tests for Python package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        py: [ '3.6', '3.7', '3.8', '3.9' ]
    steps:
      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install system dependencies
        # TODO: can we use openblas?
        run: sudo apt-get install libatlas-base-dev liblapack-dev liblapacke-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        run: make test_direct
