name: Deploy to PyPI

on:
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        openblas_version: [ '0.2.14.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_TEST_COMMAND: "python -VV && python -m unittest discover -f -s {project}/tests/test_unit/"
          CIBW_TEST_EXTRAS: "dev"
          CIBW_SKIP: "pp* cp27-* cp33-* cp34-* cp35-*"
            #CIBW_ARCHS_MACOS: x86_64 arm64 universal2
            #CIBW_ARCHS_LINUX: auto aarch64
          CIBW_BEFORE_ALL_WINDOWS: pwsh build_tools/github/setup_windows.ps1
          CIBW_BEFORE_BUILD: "pip install numpy Cython"
