name: Deploy to PyPI

on:
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        python: [37]
        openblas_version: [ '0.2.14.1' ]
        include:
          - os: windows-latest
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            bitness: 32
            platform_id: win32

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

            #      - name: Setup tmate session
            #        uses: mxschmitt/action-tmate@v3

      - name: Build and test wheels
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir} ${{ matrix.bitness }}
          CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }} ${{ matrix.bitness }}
          CIBW_TEST_COMMAND: "python -VV && python -m unittest discover -f -s {project}/tests/"
          CIBW_TEST_EXTRAS: "dev"
          CIBW_SKIP: "pp* cp27-* cp33-* cp34-* cp35-*"
          CIBW_BEFORE_ALL_WINDOWS: pwsh build_tools/github/setup_windows.ps1
          CIBW_BEFORE_BUILD: "pip install numpy Cython"
          CIBW_BUILD_VERBOSITY: 1
            #CIBW_ARCHS_MACOS: x86_64 arm64 universal2
            #CIBW_ARCHS_LINUX: auto aarch64
        run: bash build_tools/github/build_wheels.sh
