name: Deploy to PyPI

on:
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_TEST_COMMAND: "python -VV && python -m unittest discover -f -s {project}/tests/test_unit/"
          CIBW_TEST_EXTRAS: "dev"
          CIBW_SKIP: "pp* cp27-* cp33-* cp34-* cp35-*"
            #CIBW_ARCHS_MACOS: x86_64 arm64 universal2
            #CIBW_ARCHS_LINUX: auto aarch64
          CIBW_BEFORE_ALL_WINDOWS: |
            nuget install OpenBLAS -Version ${{ matrix.openblas_version }} -OutputDirectory /cibw/openblas -Verbosity detailed
            echo "[openblas]" | Out-File -FilePath ~/.numpy-site.cfg -Encoding utf8
            echo "libraries = openblas" | Out-File -FilePath ~/.numpy-site.cfg -Encoding utf8 -Append
            echo 'library_dirs = D:\cibw\openblas\OpenBLAS.${{ matrix.openblas_version }}\lib\native\lib\x64' | Out-File -FilePath ~/.numpy-site.cfg -Encoding utf8 -Append
            echo 'include_dir = D:\cibw\openblas\OpenBLAS.${{ matrix.openblas_version }}\lib\native\include' | Out-File -FilePath ~/.numpy-site.cfg -Encoding utf8 -Append
            TREE "D:\\cibw\\openblas" /F
            Rename-Item "D:\\cibw\\openblas\\OpenBLAS.${{ matrix.openblas_version }}\\lib\\native\\lib\\x64\\libopenblas.dll.a" "libopenblas.lib"
            Rename-Item "D:\\cibw\\openblas\\OpenBLAS.${{ matrix.openblas_version }}\\lib\\native\\lib\\win32\\libopenblas.dll.a" "libopenblas.lib"
            TREE "D:\\cibw\\openblas" /F
            echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg
